export type Mitglied = {
  nr: string;
  name: string;
  dlr: string;
  dienstsitz: string;
};

export const mitglieder: Mitglied[] = [
  { nr: "11001", name: "Ürzig (Würzgarten)", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11003", name: "Graach (Himmelreich)", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11004", name: "Wolf (Goldgrube)", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11009", name: "Maring-Noviand", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11021", name: "Bernkastel-Schloßberg", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11026", name: "Kröv (WG)", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11057", name: "Starkenburger Fels", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11066", name: "Oberlauf Kleine Dhron", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11067", name: "Rivenich", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11075", name: "Wehlen (Ort)", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11093", name: "Bernkastel Pallert", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11100", name: "Maring-Noviand-Honigberg", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11105", name: "Irmenach", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11108", name: "Thalfang Nord", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11113", name: "Leiwen (Bubental)", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11114", name: "Hochscheid", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11115", name: "Maring-Noviand Sonnenuhr", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11117", name: "Bernkastel-Braunes", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11118", name: "Kinheim", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11121", name: "Zeltingen - Himmelreich II", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11125", name: "Starkenburger Höhe", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11861", name: "Altrich-Platten-Wengerohr", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11880", name: "Longkamp-Kommen", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11913", name: "Bernkastel", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "11965", name: "Wehlen-Sonnenuhr", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "19003", name: "Graach (Himmelreich) - EU kofinanzierter Wegebau", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "19026", name: "Kröv (WG) - EU kofinanzierter Wegebau", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "21022", name: "Niederstaufenbach", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21036", name: "Morbach", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21037", name: "Relsberg", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21044", name: "Selchenbach", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21053", name: "Konken", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21056", name: "Schwanheim", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21066", name: "Lug", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21067", name: "Breitenbach", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21072", name: "Wörsbach", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21089", name: "Trahweiler", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21090", name: "Herschweiler-Pettersheim", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21112", name: "Elzweiler-Welchweiler", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21113", name: "Obersimten L 484", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21119", name: "Liebsthal", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21120", name: "Bayerfeld-Steckweiler", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21122", name: "Niederalben", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21126", name: "Ilbesheim", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21129", name: "Martinshöhe (Ortslage)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21130", name: "Geiselberg", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21137", name: "Bisterschied-Teschenmoschel (Wald)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21141", name: "Kottweiler-Schwanden (Wald)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21148", name: "Vogelbach (Wald)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21159", name: "Knopp-Labach", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21176", name: "Zweibrücken (Hornbach,Auerbach)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21179", name: "Reipoltskirchen", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21184", name: "Schallodenbach", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21200", name: "Imsweiler", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21201", name: "Unternehmensflurbereinigung L395 Kindsbach", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21326", name: "Heltersberg (Lindenbrunnerhof)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21480", name: "Ilbesheim (Ortslage)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21583", name: "Dannenfels (Ortslage)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21636", name: "Finkenbach-Gersweiler (Ortslage)", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21702", name: "Kottweiler-Schwanden", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "21854", name: "Schweisweiler", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "29122", name: "Niederalben - EU-kofinanzierter Wegebau", dlr: "DLR Westpfalz", dienstsitz: "Kaiserslautern" },
  { nr: "31033", name: "Walporzheim", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31064", name: "Plittersdorf (Wald)", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31080", name: "Brenk", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31083", name: "Retterath-Arbach", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "31124", name: "Gevenich", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31126", name: "Kesseling", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31127", name: "Berg (31127)", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31130", name: "Weiler", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31148", name: "Elztal I", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31162", name: "Elztal II-Monreal", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31170", name: "Mayschoß III", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31218", name: "Büchel", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31262", name: "Ulmen-Meiserich", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31270", name: "Uhlen-Hamm", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31287", name: "Oberelz-Lirstal", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "31290", name: "Ulmen-Vorpochten", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31291", name: "Auderath", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31311", name: "Lieg", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31368", name: "Kell", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31493", name: "Dernau (Flut)", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31495", name: "Mayschoß (Flut)", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31497", name: "Pommern", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "31623", name: "Kruft", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "39033", name: "Walporzheim - EU-kofinanzierter Wegebau", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Mayen" },
  { nr: "41018", name: "Friedelsheim", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41026", name: "Impflingen B 38 Nord", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41038", name: "Gleiszellen-Gleishorbach", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41049", name: "Rinnthal", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41075", name: "Schauernheim (Acker)", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41086", name: "Erpolzheim (Lpf)", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41121", name: "Annweiler-Sarnstall", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41143", name: "RPK/Stadt LU Zuwegung Gemüsegroßmärkte", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41155", name: "Freinsheim VI", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41156", name: "Gleiszellen-Gleishorbach III", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41160", name: "Weisenheim a.Sd./Lambsheim I Wg", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41163", name: "Berg Riegeldeich", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41168", name: "Dürkheimer Bruch", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41175", name: "Lambsheim Ost", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41228", name: "Impflingen B 38 Süd", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41230", name: "Weisenheim am Berg IV", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41240", name: "NGP Bienwald West (Öko)", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41243", name: "Hochstadt-Zeiskam Acker", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41245", name: "Dörrenbach B 427", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41250", name: "Bobenheim a. Bg. II", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41255", name: "Friedelsheim I", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41256", name: "Kirrweiler VII", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41258", name: "Kirrweiler VIII", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41261", name: "NGP Bienwald Ost-Minfeld/Freckenfeld", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41262", name: "Nußdorf VII Ost", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41264", name: "Nußdorf VIII", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41272", name: "Weisenheim a. Sd./Lambsheim II WG", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41273", name: "Weisenheim a. Sd./Lambsheim III", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41274", name: "Weisenheim a.Sd./Lambsheim IV", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41278", name: "Weisenheim a. Sd./Lambsheim I Obst", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41281", name: "Nußdorf VI", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41286", name: "Horbachtal", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41319", name: "Freinsheim VII", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41326", name: "Bobenheim/Weisenheim am Berg", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41334", name: "Heßheim OU L453/L520", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41344", name: "NGP Bienwald Ost-Kandel", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41352", name: "Lu-Edigheim/Altrheingraben", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41377", name: "Bellheim Südumgehung L 509", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41385", name: "Dierbach-Sand", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41397", name: "Freinsheim VIII", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41416", name: "Winden-Steinweiler", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41418", name: "Flomersheim/Frankenthaler Weg", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41436", name: "Nußdorf VII West", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41506", name: "Ungstein (Rest)", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41631", name: "Hochwasserrückhaltung Wörth-Jockgrim (Polder)", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41651", name: "St. Martin-Wingertsberg", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41784", name: "Freinsheim", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41799", name: "Weisenheim Am Berg", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41863", name: "Neustadt-Duttweiler", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41878", name: "Neupotz (Ortslage)", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41952", name: "Nußdorf II", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41972", name: "Weingarten (Ort) Teil 2", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "41985", name: "Geinsheim Süd", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "42240", name: "NGP Bienwald West", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "42631", name: "HWR Wörth-Jockgrim", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "43009", name: "Hochdorf-Assenheim - Gemüsemärkte", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "49230", name: "Weisenheim am Berg IV - EU-kofinanzierter Wegebau", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "49250", name: "Bobenheim am Berg II - EU-kofinanzierter Wegebau", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "49274", name: "Weisenheim a.Sd./Lambsheim IV - EU-kofin. Wegebau", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "49436", name: "Nußdorf VII West - EU-kofinanzierter Wegebau", dlr: "DLR Rheinpfalz", dienstsitz: "Neustadt" },
  { nr: "51024", name: "Kirchspiel-Bodenbach", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51026", name: "Lünebach", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51039", name: "Eilscheid/Lierfeld", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51040", name: "Merlscheid/Heilhausen", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51049", name: "Gondenbrett", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51062", name: "Schalkenmehren", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51063", name: "Idenheim", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51066", name: "Idesheim", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51067", name: "Harspelt", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51070", name: "Sevenig/Our", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51071", name: "Lützkampen", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51072", name: "Kyllschleife", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51077", name: "Herbstmühle/Hütten", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51078", name: "Berkoth", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51079", name: "Eschfeld", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51081", name: "Pelm/Gees", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51088", name: "Kirchspiel Welcherath", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51099", name: "Krautscheid", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51100", name: "Unternehmensflurbereinigung Nohn", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51102", name: "Struth (Wald)", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51111", name: "Udler", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51112", name: "Nord-Ost-Tangente Bitburg", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51137", name: "Euscheid/Strickscheid", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51141", name: "Roscheid", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51143", name: "Jucken", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51151", name: "Bollendorf", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51166", name: "Darscheid/Hörscheid", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51167", name: "Sülm/Scharfbillig", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51170", name: "Gondorf", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51172", name: "Oberpierscheid/Niederpierscheid/Mauel", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51175", name: "Lambertsberg", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "51184", name: "Daun-Boverath", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "52024", name: "Kirchspiel-Bodenbach (Zuw.)", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "59079", name: "Eschfeld - EU kofinanzierter Wegebau", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "59143", name: "Jucken - EU-kofinanzierter Wegebau", dlr: "DLR Eifel", dienstsitz: "Bitburg" },
  { nr: "61033", name: "Gimbweiler", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61089", name: "Boppard-Eisenbolz", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61090", name: "Bad Salzig Weiler", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61097", name: "Unteres Trauntal", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61099", name: "Manubach-Ortslage", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61111", name: "Vollmersbach", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61114", name: "Berschweiler-Dorf", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61117", name: "Dommershausen", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61129", name: "Viertälergebiet-Diebachtal", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61171", name: "Nohen", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61179", name: "Mackenrodt", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61194", name: "Diebachtal-Wald", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61198", name: "Buch", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61202", name: "Bergen", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "61213", name: "HWS Hochstetten-Dhaun", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "63003", name: "Boppard Eisenbolz Plateau", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "71002", name: "Hentern", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71025", name: "Nittel V", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71028", name: "Leuktal", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71031", name: "Langsur", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71032", name: "Trier-Tiergartental", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71067", name: "Thörnich (Ritsch)", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71068", name: "Bilzingen", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71072", name: "Farschweiler", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "71085", name: "Untere Ruwer", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71089", name: "Mehring (Blattenberg)", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "71110", name: "Nittel V, Teilgebiet 2 \"Spiesberg\"", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71114", name: "Ensch", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71116", name: "Ockfen-Schoden-Irsch", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71122", name: "Züsch-Neuhütten", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71124", name: "Detzem (WG) Teilgebiet1 \"In der Löf\"", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "71523", name: "Waldrach Ort IV", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "73009", name: "Geisfeld", dlr: "DLR Mosel", dienstsitz: "Trier" },
  { nr: "79124", name: "Detzem (WG), Teilg. 1 - EU kofinanzierter Wegebau", dlr: "DLR Mosel", dienstsitz: "Bernkastel-Kues" },
  { nr: "81020", name: "Nochern", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81021", name: "Niederbachheim", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81022", name: "Niederwallmenach", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81026", name: "Berzhausen-Seelbach", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81037", name: "Filsen", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81038", name: "Oberbachheim", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81039", name: "Winterwerb", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81069", name: "Kehlbach", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81073", name: "Neitersen-Schöneberg", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81074", name: "Großmaischeid-Kleinmaischeid", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81079", name: "Horhausen-Willroth-Krunkel", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81080", name: "Rengsdorf B 256", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81112", name: "Dachsenhausen", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81117", name: "Oberlahr-Burglahr", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81122", name: "Obersteinebach-Niedersteinebach", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81124", name: "Dornholzhausen", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81134", name: "Linz-Wald", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81155", name: "Sulzbach-Misselberg", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81159", name: "Obernhof-Weinähr", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81168", name: "Oberfischbach", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81177", name: "Dienethal", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81182", name: "Winden", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81189", name: "Rettert", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81193", name: "Berndroth", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81201", name: "Oberwies", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "81205", name: "Mittelfischbach", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "89189", name: "Rettert - EU kofinanzierter Wegebau", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "89193", name: "Berndroth - EU kofinanzierter Wegebau", dlr: "DLR Westerwald-Osteifel", dienstsitz: "Montabaur" },
  { nr: "91003", name: "Polder Ingelheim", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91203", name: "Partenheim-Projekt III", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91314", name: "Uelversheim-Aulenberg-Projekt I", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91316", name: "Uelversheim-Aulenberg Projekt III", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91318", name: "Eich", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91321", name: "Flomborn", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91405", name: "Uelversheim (Ortslage)", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91439", name: "Nierstein-Plateau", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91579", name: "Zotzenheim I", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91609", name: "Polder-Ingelheim-Projekt I", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91610", name: "Polder-Ingelheim-Projekt II", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91678", name: "Mommenheim-Projekt II", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91695", name: "Stadecken-Projekt VI", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91713", name: "Hamm", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91774", name: "Biebelnheim", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91782", name: "Zotzenheim", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91806", name: "Nierstein-Plateau-Projekt IV-", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91808", name: "Nierstein-Plateau-Proj. V", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91809", name: "Nierstein-Plateau-Proj. VI", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91810", name: "Uelversheim-Aulenberg Projekt II", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91859", name: "Ensheim", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91901", name: "Wolfsheim I", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91902", name: "Wolfsheim II", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "91984", name: "Sulzheim", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "93002", name: "Bubenheim Projekt I", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "93003", name: "Zotzenheim III", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "93004", name: "Zotzenheim II", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "99002", name: "Bubenheim Projekt I - EU kofinanzierter Wegebau", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
  { nr: "99316", name: "Uelversheim-Aulenberg Projekt III - EU-kof. Wegeb.", dlr: "DLR Rheinhessen-Nahe-Hunsrück", dienstsitz: "Bad Kreuznach" },
];
